version: "3.1"

services:
    wordpress:
        build: .
        restart: always
        image: wordpress
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes:
             - ./wordpress:/var/www/html/

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql

    adminer:
        depends_on:
            - db
        image: adminer
        restart: always
        ports:
            - 8888:8080

networks:
    back:

volumes:
    wordpress:
    db:
